// Code generated by MockGen. DO NOT EDIT.
// Source: wallet_handler.go

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWalletStorage is a mock of WalletStorage interface.
type MockWalletStorage struct {
	ctrl     *gomock.Controller
	recorder *MockWalletStorageMockRecorder
}

// MockWalletStorageMockRecorder is the mock recorder for MockWalletStorage.
type MockWalletStorageMockRecorder struct {
	mock *MockWalletStorage
}

// NewMockWalletStorage creates a new mock instance.
func NewMockWalletStorage(ctrl *gomock.Controller) *MockWalletStorage {
	mock := &MockWalletStorage{ctrl: ctrl}
	mock.recorder = &MockWalletStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletStorage) EXPECT() *MockWalletStorageMockRecorder {
	return m.recorder
}

// CreateCard mocks base method.
func (m *MockWalletStorage) CreateCard(ctx context.Context, userToken string, d *CardData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCard", ctx, userToken, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCard indicates an expected call of CreateCard.
func (mr *MockWalletStorageMockRecorder) CreateCard(ctx, userToken, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCard", reflect.TypeOf((*MockWalletStorage)(nil).CreateCard), ctx, userToken, d)
}

// DeleteCard mocks base method.
func (m *MockWalletStorage) DeleteCard(ctx context.Context, userToken string, d *CardData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", ctx, userToken, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCard indicates an expected call of DeleteCard.
func (mr *MockWalletStorageMockRecorder) DeleteCard(ctx, userToken, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockWalletStorage)(nil).DeleteCard), ctx, userToken, d)
}

// ListCard mocks base method.
func (m *MockWalletStorage) ListCard(ctx context.Context, userToken string) ([]*CardData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCard", ctx, userToken)
	ret0, _ := ret[0].([]*CardData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCard indicates an expected call of ListCard.
func (mr *MockWalletStorageMockRecorder) ListCard(ctx, userToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCard", reflect.TypeOf((*MockWalletStorage)(nil).ListCard), ctx, userToken)
}
